config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show]
  resources :users, only: :index

  # devise_for :users
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # root to: "users#new"
  # get "/auth/:provider/callback" => "sessions#create"
  # get "/signout" => "sessions#destroy", :as => :signout
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  # belongs_to :user

  validates :description, length: { minimum: 50, too_short: "Answer description must be at least %{count} characters long." }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  # belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, length: { minimum: 40, too_short: "Title must be at least %{count} characters long." }
  validates :description, length: { minimum: 150, too_short: "Description must be at least %{count} characters long." }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  validates :uid, uniqueness: true
  validates :username, presence: true
  validates :provider, presence: true
  # validates :email, presence: true
  # validates :email, format: { with: /.+@.+\..+/ }
  # validates :avatar_url, presence: true
  #
  # devise :omniauthable, :omniauth_providers => [:github]


  # def self.find_or_create_from_omniauth(auth)
  #   provider = auth.provider
  #   uid = auth.uid
  #
  #   find_or_create_by(provider: provider, uid: uid) do |user|
  #
  #     user.provider = provider
  #     user.uid = uid
  #     user.email = auth.info.email
  #     user.username = auth.info.name
  #     user.save!
  #     # user.avatar_url = auth.info.image
  #   end
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.name
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answer
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @user = User.find(1)
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Answer submitted successfully"
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to submit answer."
      render :new
    end
  end

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order(:created_at).reverse_order
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(:created_at).reverse_order

    # Add votes to answers;
    # Have link/button to increment votes if voted for
    
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
    edit_question_path(@question)
  end

  def create
    @question = Question.new(question_params)
    @user = User.find(1)

    if @question.save
      flash[:success] = 'Your question has been posted.'
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      flash[:success] = 'Question has been updated.'
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy

    @question = Question.find(params[:id])

    if @question.destroy
      flash[:success] = 'Question has been deleted.'
      redirect_to questions_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # auth = request.env["omniauth.auth"]
    # user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<h2>New Answer for <%= @question.title %></h2>

<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
  <div id="error_explanation">
    <h3>There are <span class="error"><%= @answer.errors.count %> errors</span> in your submission. Please retry.</h3>

    <ul>
      <% @answer.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/answers/show.html.erb
<div class="answer">
  <p class="description">
    <strong>Answers:</strong>

    <%= @answer.description %>
  </p>

  <% unless @question.user.nil? %>
    Answered by: <%= @question.user.username %>
  <% end %>
</div>

app/views/layouts/_topbar.html.erb
<div class="top-bar">

  <div class="left">
    <%= link_to "Rescue", questions_path, id: "logo" %><%= link_to "Mission", questions_path, id: "logo-light" %>
  </div>

  <ul class="sign-in">
    <% if current_user %>
      <li>Signed in as <%= current_user.username %></a></li>
      <li> <%= link_to "Sign Out", signout_path, id: "sign_out" %></li>
    <% else %>
      <li> <%= link_to "Sign In with Facebook", "/auth/facebook", id: "sign_in" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rescue Mission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'facebook' %>
  </head>

  <body>

    <%= render 'layouts/topbar' %>

    <%= yield %>


  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
  <div id="error_explanation">
    <h3>There are <span class="error"><%= @question.errors.count %> errors</span> in your submission. Please retry.</h3>

    <ul>
      <% @question.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2 class="form-title">Edit Question</h2>

<%= render 'form' %>

<div class="links">
<%= link_to 'Show', @question %> |
<%= link_to 'Back', question_path %>
</div>

app/views/questions/index.html.erb
<ul>
  <h1>Questions</h1>

  <% @questions.each do |question| %>
    <li><%= link_to "#{question.title}", question %></li>
  <% end %>


  <p> <%= link_to "Ask a New Question", new_question_path %></p>
</ul>

app/views/questions/new.html.erb
  <h2 class="form-title">Ask a New Question!</h2>

  <%= render 'form' %>

  <div class="links">
    <%= link_to 'Back', questions_path %>
  </div>

app/views/questions/show.html.erb
<div class="question">
  <p class="title">
    <strong>Question:</strong>
    <%= @question.title %><br>

  </p>

  <p class="description"><%= @question.description %></p>

  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure you want to delete this question?' } %>
</div>


  <div class="answers">
    <h3><strong>Answers:</strong></h3>
    <% @answers.each do |answer| %>
      <p><%= answer.description %></p>
    <% end %>
  </div>



<div class="links">
  <%= link_to 'Post an Answer', new_question_answer_path(@question, @answer) %> |
  <%= link_to 'Back', questions_path %>
</div>